version: '3.7'
services:
  postgres:
    image: 'postgres:11.5'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=talentland
      - POSTGRES_DB=talentdb
      - POSTGRES_PASSWORD=donitas123
      - PGDATA=/var/lib/postgresql/data/pgdata
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: .
    init: true
    restart: unless-stopped
    ports:
      - '5000:5000'
    volumes:
      - .:/app/node_app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - notused:/app/node_modules
    environment:
      - TZ=America/Mazatlan
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - PGUSER=talentland
      - PGHOST=postgres
      - PGDATABASE=talentdb
      - PGPASSWORD=donitas123
      - PGPORT=5432

volumes:
  notused: